"""add_creator_id_to_lots

Revision ID: 16bb99695331
Revises: 4c53c89b9215
Create Date: 2026-07-12 10:35:17.259562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16bb99695331'
down_revision: Union[str, Sequence[str], None] = '4c53c89b9215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Добавляем колонку как nullable сначала
    op.add_column('lots', sa.Column('creator_id', sa.Integer(), nullable=True))

    # 2. Заполняем существующие записи — ставим id=1 (или любого существующего юзера)
    op.execute('UPDATE lots SET creator_id = 1 WHERE creator_id IS NULL')

    # 3. Добавляем foreign key
    op.create_foreign_key(None, 'lots', 'users', ['creator_id'], ['id'])

    # 4. Делаем NOT NULL
    op.alter_column('lots', 'creator_id', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lots', type_='foreignkey')
    op.drop_column('lots', 'creator_id')
    # ### end Alembic commands ###
