"""Краткое описание изменений

Revision ID: efe35ac56081
Revises: 71d38ea19bc5
Create Date: 2026-07-21 13:01:51.725868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe35ac56081'
down_revision: Union[str, Sequence[str], None] = '71d38ea19bc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lots', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lots', 'image_url')
    # ### end Alembic commands ###
